spring:
  application:
    name: profile
  datasource:
    url: jdbc:mysql://localhost:3306/rentDB?createDatabaseIfNotExist=true
    username: root
    password: admin1
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
security:
  oauth2:
    resource:
      token-info-uri: http://127.0.0.1:9191/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin